version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: strvdb
    ports:
      - "5432:5432"

  newsletter:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: strvdb
      API_PORT: 8080
      JWT_KEY: my_secret_key
    # Optional if using traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strv.rule=Host(`strv.mb.marstad.cz`)"
      - "traefik.http.services.strv.loadbalancer.server.port=8080"
      - "traefik.http.routers.strv.service=strv"
